let operands = []; // represents the operand(s) currently on the screen
let operator = " "; // represents the current operators of the operation displayed
let resultState = true; // set to true when the display (exclusively) contains output generated by the calculator
let errorState = false; // set to true when an erroneous calculation is attempted

let digitButtons = document.querySelectorAll(".number");
let operatorButtons = document.querySelectorAll("#buttons #controls button");
let display = document.querySelector("#display > input");
let clearButton = document.querySelector("#clear");
let equalButton = document.querySelector("#equal");
let backspaceButton = document.querySelector("#backspace");
let decimalButton = document.querySelector("#decimal");
let signChangeButton = document.querySelector("#signChange");

const add = (x, y) => x + y;
const subtract = (x, y) => x - y;
const multiply = (x, y) => x * y;
const divide = (x, y) => x / y;

const operate = (x, y, operator) => {
    console.log(" ");
    console.log("operate()");
    console.log(x);
    console.log(y);
    console.log(operator);
    switch (operator) {
        case "+":
            return add(+x, +y);
        case "-":
            return subtract(+x, +y);
        case "x":
            return multiply(+x, +y);
        case "/":
            if (+y !== 0) {
                console.log("not 0, good");
                return divide(+x, +y);
            }
        case " ":
            if (x !== undefined && y === undefined) {
                return x;
            }
    }
};

digitButtons.forEach((button) => {
    button.addEventListener("click", () => {
        // if ERROR or the result of an operation is on the screen, entering a digit should clear the display
        // before adding that number to the screen
        if (errorState || resultState) {
            display.value = "";
            resultState = false;
            errorState = false;
        }
        display.value += button.innerText;
    });
});

signChangeButton.addEventListener("click", () => {
    if (!errorState && latestOperand() !== "" && latestOperand() !== "0") {
        const operatorList = display.value.split(operator);
        const operandsExceptLast = operands.join("").trim();
        if (operator === "-") {
            display.value = operandsExceptLast + "+" + latestOperand();
            operator = "+";
        }

        // look at the latest operand. if it is not prefixed by a -, then prefix it with -. If it is, then
        // remove the -. Here the - should not count as an operator
        else if (latestOperand().at(0) === "-") {
            display.value = operandsExceptLast + (operator === " " ? "" : operator) + latestOperand().slice(1);
        } else {
            display.value = operandsExceptLast + (operator === " " ? "" : operator) + "-" + latestOperand();
        }
        resultState = false;
    }
});

decimalButton.addEventListener("click", () => {
    // should only be applied when the current operand does not contain a decimal already
    if (!errorState && !latestOperand().includes(".")) {
        const operandsExceptLast = operands.join("").trim();
        const lastOperand = (latestOperand() === "" ? "0" : latestOperand()) + ".";
        display.value = operandsExceptLast + (operator === " " ? "" : operator) + lastOperand;
        resultState = false;
    }
});

operatorButtons.forEach((button) => {
    if (!["clear", "equal", "backspace"].includes(button.id)) {
        button.addEventListener("click", () => {
            // if ERROR is on screen, user should not be allowed to enter an operator
            // if the result of an operation is on the screen, user should be allowed to follow
            // it with an operator
            if (errorState) {
                display.value = "";
                errorState = false;
            }

            evalOperation();
            operands = [display.value];
            display.value += button.innerText;
            operator = button.innerText;
            resultState = false;
        });
    }
});

clearButton.addEventListener("click", () => {
    display.value = "0";
    operands = [];
    operator = " ";
    resultState = true;
});

const latestOperand = () => display.value.split(operator).at(-1);

const evalOperation = () => {
    // nothing to evaluate if error or result is on the screen
    if (!(errorState || resultState)) {
        operands.push(latestOperand());
        const validOperands = operands.reduce(
            (allNumeric, current) => allNumeric && !isNaN(current) && !isNaN(parseFloat(current)),
            true
        );

        if (validOperands && operands.length === 2) {
            console.log(operator);
            // we must evaluate the operation
            const operationRes = operate(operands[0], operands[1], operator);
            console.log(operationRes);
            if (operationRes === undefined) {
                return false;
            }
            display.value = operationRes;
            operator = " ";
            operands = [];
            resultState = true;
            return true;
        }
        return false;
    }
    return false;
};

equalButton.addEventListener("click", () => {
    if (!evalOperation()) {
        errorState = true;
        display.value = "ERROR";
        operands = [];
        operator = " ";
    }
});

backspaceButton.addEventListener("click", () => {
    if (!(errorState || resultState)) {
        display.value = display.value.substr(0, display.value.length - 1);
        if (display.value === "") {
            display.value = "0";
            resultState = true;
        }
    }
});
